-- MySQL Script generated by MySQL Workbench
-- 04/06/17 00:04:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specialist` (
  `idspecialist` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `idservice` INT NULL,
  `idregion` INT NULL,
  `rate` INT NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`idspecialist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `vorname` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `idregion` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `specialist_idspecialist` INT NOT NULL,
  PRIMARY KEY (`idregion`, `specialist_idspecialist`),
  INDEX `fk_region_specialist1_idx` (`specialist_idspecialist` ASC),
  CONSTRAINT `fk_region_specialist1`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `mydb`.`specialist` (`idspecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `idservice` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `specialist_idspecialist` INT NOT NULL,
  PRIMARY KEY (`idservice`, `specialist_idspecialist`),
  INDEX `fk_service_specialist1_idx` (`specialist_idspecialist` ASC),
  CONSTRAINT `fk_service_specialist1`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `mydb`.`specialist` (`idspecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rate` (
  `idrate` INT NOT NULL,
  `rate` INT NULL,
  `comment` VARCHAR(150) NULL,
  `customer_idcustomer` INT NOT NULL,
  `specialist_idspecialist` INT NOT NULL,
  PRIMARY KEY (`idrate`, `customer_idcustomer`, `specialist_idspecialist`),
  INDEX `fk_rate_customer_idx` (`customer_idcustomer` ASC),
  INDEX `fk_rate_specialist1_idx` (`specialist_idspecialist` ASC),
  CONSTRAINT `fk_rate_customer`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_specialist1`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `mydb`.`specialist` (`idspecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idrole` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `idaccount` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `customer_idcustomer` INT NOT NULL,
  `specialist_idspecialist` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`idaccount`, `customer_idcustomer`, `specialist_idspecialist`, `role_idrole`),
  INDEX `fk_account_customer1_idx` (`customer_idcustomer` ASC),
  INDEX `fk_account_specialist1_idx` (`specialist_idspecialist` ASC),
  INDEX `fk_account_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_account_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_specialist1`
    FOREIGN KEY (`specialist_idspecialist`)
    REFERENCES `mydb`.`specialist` (`idspecialist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `mydb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
